package com.itech4kids.mc.headhunt.Objects;

public enum PerksType {

    ARROW_RECOVERY,
    BLAZING_ARROWS,
    BULLDOZER,
    JUGGERNAUT,
    MARKSMANSHIP,
    RESISTANCE_BOOST,
    KNOWLEDGE,
    SAVIOR,
    LUCKY_CHARM,
    BLACK_MAGIC,
    BARBARIAN,
    TELEKINESIS,
    FIRE_ASPECT,
    ARROW_SILVERFISH,
    GAUNTLET,
    WEAKNESS,
    DIAMOND,
}
